### ISSUE TITLE
[Doc] Useful links

### ISSUE THREAD

**Issue by gglin001** [PFCCLab/paddlefx#5]
# Useful links

PEP-523
https://peps.python.org/pep-0523/

NEP-18
https://numpy.org/neps/nep-0018-array-function-protocol.html

`__torch_function__`
https://github.com/pytorch/rfcs/blob/master/RFC-0001-torch-function-for-methods.md

torchdynamo
https://github.com/pytorch/torchdynamo
https://github.com/pytorch/pytorch/tree/master/torch/_dynamo
https://github.com/pytorch/pytorch/tree/master/torch/csrc/dynamo

torch.fx
https://github.com/pytorch/pytorch/tree/master/torch/fx
https://arxiv.org/abs/2112.08429

functorch
https://github.com/pytorch/pytorch/tree/master/torch/_functorch

functorch/aot_autograd
https://github.com/pytorch/pytorch/blob/master/torch/_functorch/aot_autograd.py

paddleconverter
https://github.com/zhouwei25/paddleconverter

onefx
https://github.com/Oneflow-Inc/one-fx

**Comment by jzhang533** [comment]
an attempt of tracing in PaddleSlim by @wanghaoshuang : 
https://github.com/PaddlePaddle/PaddleSlim/pull/1667/files#diff-43ce05df8ee3bdf9c3b7e574789ba47a948afb529f8ce8838f8a53193b3e2713

**Comment by sanbuphy** [comment]
Some Chinese links about fx:
用沐神的方法阅读PyTorch FX论文:
https://mp.weixin.qq.com/s/JENCa_GNGPHhOspGb79ugA
适配PyTorch FX，OneFlow让量化感知训练更简单
https://mp.weixin.qq.com/s/O8yGUuTL-o_gHQV4xez_nQ
torch.fx原理解读（一）symbolic trace浅析
https://zhuanlan.zhihu.com/p/546872220?spm=wolai.workspace.0.0.56462e3fHzTc6x
实践 torch.fx 第一篇——基于 Pytorch 的模型优化量化神器
https://www.cvmart.net/community/detail/6230

**Comment by jzhang533** [comment]
- [PyTorch 2.0 Backend Integration](https://github.com/pytorch/workshops/blob/master/NeurIPS_2022/PyTorch%202.0%20Backend%20Integration%20-%20NeurIPS%202022.pdf) & [jupyter notebook](https://colab.research.google.com/drive/1Zh-Uo3TcTH8yYJF-LLo5rjlHVMtqvMdf)
